### ISSUE TITLE
Missing pictures in Chosen/Broken character sheets

### ISSUE THREAD

**Issue by krielgn** [joesinghaus/Band-of-Blades#2]
After uploading an avatar image for Zora, the image in the character sheet would not load. I tried removing the avatar and restarting roll20, but this had no effect. I'm not sure if the issue could be related, but when opening any Broken pages, sometimes their images do not load either. If I leave roll20 and rejoin, sometimes different Broken images successfully load, but it seems random.

**Comment by joesinghaus** [comment]
Sorry, looks like you have some trouble loading the images, but since it works sometimes and sometimes doesn't, it looks like an infrastructure issue that I have no control over.
