### ISSUE TITLE
Missing attributes from Quartermaster sheet 

### ISSUE THREAD

**Issue by watergoesred** [joesinghaus/Band-of-Blades#4]
Hi

Just something minor on the Quartermaster character sheet. I'm trying to use your Blades Companion script to link to quantities of different Materiel, which requires linking to the relevant attribute. But no attributes appear on the Attributes and Abilities tab for Horses, Blackshot, or Religious Supplies. All the other Materiel have attributes or have them appear after I fill them in on the sheet.

Is there any way to ensure these three Materiel terms (all have 2 or 3 rows each) have attributes appear?

Thanks
Oliver

**Comment by joesinghaus** [comment]
The reason that they are invisible is that they are in a repeating section, and for some reason Roll20 does not display those in the last tab.

If you know how to pull repeating attributes out of a sheet, the attributes are named after this pattern:
```
repeating_materiel_${id}_name
repeating_material_${id}_check
repeating_material_${id}_uses
```

**Comment by watergoesred** [comment]
Thanks!

I got pretty close to working that out last night. I pulled up the Github
html and read up about repeating sections. It still couldn’t get it to
work.

But from your email, I think I see my mistake. I was using _attr_uses at
the end:
!blades add-by-token repeating_materiel_$0_attr_uses

I think I’ll try:
!blades add-by-token repeating_materiel_$0_uses

Cheers

**Comment by watergoesred** [comment]
Still no luck pull the attributes from the Materiel repeating section.

I think I’m getting the !blades function right as it’s working with all
other attributes listed on the last tab.

I thought:
blades add-by-token repeating_materiel_$0_uses

would link to the top horses circle dots and:
blades add-by-token repeating_materiel_$1_uses

would link to the top blackshot circle dots. But I can’t see how either
links to those or any other values in the materiel repeating.

So I can only assume I’m misunderstanding what you mean by ${id}.

**Comment by watergoesred** [comment]
I got it working by inspecting the HTML script for each repeating
section and finding its specific alphanumeric ID.

For example:
!blades add-by-token repeating_materiel_-M38Dkb8kZTtl1n18Vpf_uses

I don't know if that is what you meant or if it's a good way to do it, but
it's working for the moment.

**Comment by joesinghaus** [comment]
Yes, that's what I meant! Sorry that I have been pretty busy and not very responsive.

**Comment by watergoesred** [comment]
Good to know and no worries! I nutted it out eventually. Both your sheet and your script are great. Cheers!
