### ISSUE TITLE
Roll Template Background Issues

### ISSUE THREAD

**Issue by CaptainScott0** [joesinghaus/Band-of-Blades#5]
The Roll Templates in Roll20 are broken and the backgrounds are not displaying properly, leading some sections to be completely unreadable.

For example, this is the result when performing a **Fortune Roll**:
![Annotation 2020-04-11 182019](https://user-images.githubusercontent.com/63512856/79050327-30a36100-7c21-11ea-84da-a9320ac8263e.png)

And this is the result when performing an **Engagement Roll**:
![Annotation 2020-04-11 182032](https://user-images.githubusercontent.com/63512856/79050337-41ec6d80-7c21-11ea-82df-55ec7759191b.png)

This has been tested on multiple browsers, including Chrome, Opera, and IE. All of my players are experiencing this same issue.

This issue looks to have been posted about 27 days ago in the Roll20 Character Sheet Github, but hasn't been posted here from what I've seen.

**Comment by joesinghaus** [comment]
It looks like there are some issues with either Github hosting of images through their image proxy. Your best bet is probably to escalate this to the Roll20 team. Their official advice is to host sheets assets on Github, so they should make this work! The images are still present on Github and they load just fine if they are served directly and not through Roll20's proxy.

**Comment by joesinghaus** [comment]
I opened a new bug in the Roll20 repository and pinged one of the Roll20 people to take a look.

**Comment by CaptainScott0** [comment]
Much appreciated, thank you!

**Comment by kil9** [comment]
Is there any chance to replace animated GIFs to non-animated images at least until it's fixed by Roll20? I can't even guess how long it will takes, and we are still having background issues.
