### ISSUE TITLE
Marshal Engagement rolls are coming up blank

### ISSUE THREAD

**Issue by Maruvinji** [joesinghaus/Band-of-Blades#7]
Hi,

I don't know if this is an ongoing issue but my game group on Roll20 has the same issue when the Marshal rolls an engagement roll. All of us re getting a blank white screen and we have to hover over it to get the result. I have attached a screenshot below. I currently use a Mac/Chrome, my players use Windows/Chrome or Firefox we get the same issue across our systems. All other rolls shows up fine. 

![Marshall Engagement Rolls](https://user-images.githubusercontent.com/78268908/106360754-50914600-6355-11eb-8e12-d74b4e211700.png)

Regards,

Maruvinji

**Comment by joesinghaus** [comment]
That's probably another problem with the Roll20 image proxy, it keeps being broken in various ways for GIFs (and this is a GIF). Is this still a problem?

**Comment by joesinghaus** [comment]
Either way, I'm sending https://github.com/Roll20/roll20-character-sheets/pull/8377 to fix this.
